### ISSUE TITLE
Judging submission failed during github jobs due to `db.json` uploaded to sherlock-judging repo

### ISSUE THREAD

**Issue by pratraut** [aviggiano/judgementalist#6] opened 2023-06-19 17:38 UTC
We need to create `.gitignore` file, ignoring `db.json` file whenever user executes `npx judgementalist` inside judging repo. In last moment i submit all those files in a hurry and found github job got failed that validates file system format of sherlock. 

This is the error:
<img width="756" alt="Screenshot 2023-06-19 at 11 06 59 PM" src="https://github.com/aviggiano/judgementalist/assets/94991321/b60aff16-94d0-47c1-bd5e-4286e11dfcf5">

**Comment by aviggiano** [comment] 2023-06-19 17:46
Hey
Thanks for trying this out and thanks for opening this issue.
I agree, I'll implement your suggestion right now

**Comment by aviggiano** [comment] 2023-06-19 17:47
Actually, I just noticed the problem is that `db.json` is created on the repo we run `npx`, so it's not a matter of changing the `.gitignore`.
I think a better alternative will be moving this to the user's `tmp` folder. What do you think?

**Comment by pratraut** [comment] 2023-06-19 17:59
I am not sure if `/tmp` folder is persistent across system restart. If not, user will loose all the marked issue i.e., `db.json`. 

As you are creating `db.json` upon executing `npx judgementalist`, i think, it will be a good idea to create/update(if existing) `.gitignore` file.

**Comment by pratraut** [comment] 2023-06-19 18:06
I think, even with suggested solution, `.gitignore` will be committed to judging repo and then it will be same problem. Need to think of a better way. What if we can remove `db.json` when user finalize 🚀 . This button should be clicked only when user done with judging.

**Comment by pratraut** [comment] 2023-06-19 19:33
We can use sherlock's `.data` directory to store our `db.json`. It contains python scripts to check and validate folder structure. This is the code where its ignoring some standard files during validating. So we can use `.data` to store `db.json`.

https://github.com/sherlock-audit/2023-03-teller-judging/blob/4f5718e7c169cfcfe69330927716012d5f7111aa/.data/validate_filesystem.py#L22-L26
```python
        items = [
            x
            for x in os.listdir(path)
            if x not in [".data", ".git", ".github", "README.md", "Audit_Report.pdf"]
        ]
```

**Comment by aviggiano** [comment] 2023-06-19 20:17
> We can use sherlock's `.data` directory to store our `db.json`. It contains python scripts to check and validate folder structure. This is the code where its ignoring some standard files during validating. So we can use `.data` to store `db.json`.
> 
> https://github.com/sherlock-audit/2023-03-teller-judging/blob/4f5718e7c169cfcfe69330927716012d5f7111aa/.data/validate_filesystem.py#L22-L26
> 
> ```python
>         items = [
>             x
>             for x in os.listdir(path)
>             if x not in [".data", ".git", ".github", "README.md", "Audit_Report.pdf"]
>         ]
> ```

Good solution, I'll do that

**Comment by pratraut** [comment] 2023-06-19 20:42
Hey i have implemented solution for this. Can i contribute? I am getting permission error when trying to push changes to a branch.
```
moved_db_to_dot_data_dir ~/judgementalist> git push origin moved_db_to_dot_data_dir
remote: Permission to aviggiano/judgementalist.git denied to pratraut.
fatal: unable to access 'https://github.com/aviggiano/judgementalist.git/': The requested URL returned error: 403
exit 128
moved_db_to_dot_data_dir ~/judgementalist> 
```

**Comment by aviggiano** [comment] 2023-06-19 21:29
@pratraut sure, a PR would be much appreciated

I believe you need to first fork the repo, then push it to your repo, then submit a PR

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Closed** 2023-06-20 10:22 UTC
